export const CART_TITLE = 'Корзина';
export const DELETE_ITEM_TITLE = 'Видалити товар';
export const DELETE_ALL_ITEMS_TITLE = 'Видалити все';
export const MAKE_ORDER_TITLE = 'Створити замовлення';
export const THANK_YOU_TITLE = 'Введіть email';
export const CONFIRM_EMAIL = 'Підтвердити';
export const PRICE_TITLE = 'Price: $';
export const GOOD_EMAIL_TITLE = 'Your email looks good!';
export const BAD_EMAIL_TITLE = 'Please enter a valid email!';
