export const SHOP_ITEMS = [
  {
    id: 1,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 1,
    skinSection: 1,
    amount: 1,
  },
  {
    id: 2,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit2',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 2,
    skinSection: 1,
    amount: 1,
  },
  {
    id: 3,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit3',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 1,
    skinSection: 2,
    amount: 1,
  },
  {
    id: 4,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit4',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 1,
    skinSection: 1,
    amount: 1,
  },
  {
    id: 5,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit5',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 2,
    skinSection: 2,
    amount: 1,
  },
  {
    id: 6,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit6',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 1,
    skinSection: 3,
    amount: 1,
  },
  {
    id: 7,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit7',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 2,
    skinSection: 1,
    amount: 1,
  },
  {
    id: 8,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit8',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 1,
    skinSection: 2,
    amount: 1,
  },
  {
    id: 9,
    img: 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg',
    title: 'fruit9',
    description: 'Very delicious fruit, juicy',
    price: '100$',
    section: 2,
    skinSection: 3,
    amount: 1,
  },
];
export const SECTIONS = [
  {
    id: 1,
    title: 'СИРОВАТКИ',
  },
  {
    id: 2,
    title: 'ЗВОЛОЖЕННЯ',
  },
  {
    id: 3,
    title: 'ПЕПТИДИ',
  },
  {
    id: 4,
    title: 'СОНЦЕЗАХИСТ',
  },
  {
    id: 5,
    title: 'ОЧИЩЕННЯ',
  },
  {
    id: 6,
    title: 'ВІДЛУЩУВАННЯ',
  },
  {
    id: 7,
    title: 'ТОНІКИ',
  },
  {
    id: 8,
    title: 'МАСКИ',
  },
];
export const SKIN_SECTIONS = [
  {
    id: 1,
    title: 'СУХА ШКІРА',
  },
  {
    id: 2,
    title: 'НОРМАЛЬНА ШКІРА',
  },
  {
    id: 3,
    title: 'ЖИРНА ШКІРА',
  },
];
